apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: smarthotel-web 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: smarthotel-web 
    spec:
      containers:
        - name: smarthotel-web 
          image: smarthotel.azurecr.io/smarthotel-web 
          ports:
          - containerPort: 3000